//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcSJira.Models
{
    using System;
    using System.Collections.Generic;
    using DomainClasses.Interfaces;
    using DomainClasses.Bases;
    using SJiraShared;

    public class IssueCreateModel 
    {


        public System.Guid Id { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public Nullable<int> IssueTypeId { get; set; }

        public string Code { get; set; }
        public string Summary { get; set; }
        public string Description { get; set; }
        public string Environment { get; set; }
        public string Attachement { get; set; }
        public string Labels { get; set; }
        
      
        public Nullable<int> IssuePriorityId { get; set; }
        
        //public Nullable<int> IssueResolutionId { get; set; }
        public Nullable<int> TimeOriginalIstimate { get; set; }
        public Nullable<int> AssigneeId { get; set; }

        public Nullable<System.DateTime> CreatedDate { get; set; }
       

    }
}
