//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcSJira.Models
{
    using System;
    using System.Collections.Generic;
    using DomainClasses.Interfaces;
    using DomainClasses.Bases;
    using SJiraShared;

    public class My_Open_Issues_Model 
    {


        public System.Guid Id { get; set; }
      
        public string Key { get; set; }
        public string Summary { get; set; }
        public string Assignee { get; set; }
        public string Reporter { get; set; }
        public string Status { get; set; }
        public string Resolution { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public Nullable<System.DateTime> Due { get; set; }


    }
}
