//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SJiraCore.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using SJiraShared;


    public class Project : Entity<int>
    {
        public string Name { get; private set; }
 
        public String Code { get; set; }
        public Project(int id)
        {
           
        }

        protected Project() //required for EF
        {
        }
    }
}
