//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SJiraCore.Models
{
    using System;
    using System.Collections.Generic;
    using SJiraShared;
    //using System.ComponentModel.DataAnnotations;
    //using System.ComponentModel.DataAnnotations.Schema;
    //using SJiraDomainClasses.Interfaces;
 
    public class Status : Entity<int>
    {  
        public virtual string Name { get; set; }

        public Status(int id)
            : base(id)
        {
        }
    }
}
