//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SJiraCore.Models
{
    using System;
    using System.Collections.Generic;
    using SJiraShared;

    public  class UserProfile : Entity<int>
    {
        public UserProfile(int id)
            : base(id)
        {
        }
        public string UserName { get; set; }
        private UserProfile()
        {

        }
    }
}
